name: Deploy to server

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup
        uses: action/setup-node@v4
        with:
         node-version: 18
        
      - name: Install dependencies
        run: npm install

      - name: Run test
        run: npm run test

      - name: Build page
        run: npm run build
    
      - name: Deploy to Azure
        uses: Azure/static-web-apps-deploy@v1
        with:
         azure_static_web_apps_api_token: ${{secrets.AZURE_TOKEN}}
         app_location: "public"
         deployment_action: "upload"

        