name: Deploy to server

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
     - name: Print variable
       run: echo "{{ secret.TOKEN_SECRET }}"

     - name: setup
       uses: actions/setup-node@v4
       with:
        node-version: '18'
    
    