name: Deploy to server

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    env: 
     NAME: Joey Melendez
    
    steps:
     - name: Hola Mundo
       run: echo "Hola Mundo $NAME"

     - name: Working dir
       run: ls -al
       
     - name: Actions
       uses: actions/checkout@v4
    
     - name: Working dir afeter actions
       run: ls -al

  second_job:
    if: ${{ github.ref == 'refs/heads/main'}}
    needs: first_job
    runs-on: ubuntu-latest
    
    steps:
     - name: Hola Mundo
       run: echo "Hola Mundo ${{github.ref}}"